@RequestApi_HostAddress = http://localhost:5001

### Deposit $1000 to account
POST {{RequestApi_HostAddress}}/api/accounts/acct-001/transactions
Content-Type: application/json

{
  "type": "debit",
  "amount": 2000.00,
  "description": "Initial debit"
}

### Deposit $500 to account
POST {{RequestApi_HostAddress}}/api/accounts/acct-001/transactions
Content-Type: application/json

{
  "type": "credit",
  "amount": 500.00,
  "description": "Paycheck"
}

### Debit $200 from account
POST {{RequestApi_HostAddress}}/api/accounts/acct-001/transactions
Content-Type: application/json

{
  "type": "debit",
  "amount": 200.00,
  "description": "Grocery store"
}

### Health check
GET {{RequestApi_HostAddress}}/health
Accept: application/json
